country=KE
currency=KES
client-id=uG3IodFlGI09s822rwTiMApb6QK1aHnkxYCt8ED46NJzLrEk
client-secret=Ps6FSRslK7YwJHl2WneaKVFiy4oSzBCgFAzY5zhGmmxgC9QVYjN1r3D6Bv8SG04Z
auth-url=https://openapiuat.airtelkenya.com/auth/oauth2/token
payment-url=https://openapiuat.airtelkenya.com/merchant/v1/payments
query-url=https://api.safaricom.co.ke/mpesa/transactionstatus/v1/query
